name: auto main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Update Deny Host
        run: |
          pwd
          python main.py

      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'main'
          commit_message: 'Update Host'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Checkout IPv6 Branch
        uses: actions/checkout@v2
        with:
          ref: ipv6
          path: ipv6

      - name: Sync Config File
        run: |
          cp conf/config.json ipv6/conf/config.json
          cd ipv6
          git config user.email "noreply@example.com"
          git config user.name "GitHub Actions"
          git add conf/config.json
          git commit -m 'Sync config.json from main to ipv6'
          git push origin ipv6

